#include <bits/stdc++.h>
using namespace std;
#define int long long
#define pii pair<int, int>
#define vi vector<int>
#define vii vector<vector<int>>
#define mii map<int, int>
#define ios ios::sync_with_stdio(0);cin.tie(0);cout.tie(0)
const int MOD = 1e9+7;

// function is generated by GPT
void generateGrayCode(int n, vector<string> &result) {
    if (n == 1) {
        result.push_back("0");
        result.push_back("1");
    } else {
        generateGrayCode(n - 1, result);
        int size = result.size();
        for (int i = size - 1; i >= 0; --i) {
            result.push_back(result[i]);
        }
        for (int i = 0; i < size; ++i) {
            result[i] = "0" + result[i];
            result[i + size] = "1" + result[i + size];
        }
    }
}

int32_t main() 
{
    ios;
    int n; cin >> n;
    
    vector<string> grayCode;
    generateGrayCode(n, grayCode);

    for (const auto &code : grayCode) {
        cout << code << '\n';
    }

    return 0;
}
