#include <bits/stdc++.h>
using namespace std;
#define int long long
#define pii pair<int, int>
#define vi vector<int>
#define vii vector<vector<int>>
#define mii map<int, int>
#define ios ios::sync_with_stdio(0);cin.tie(0);cout.tie(0)
const int MOD = 1e9+7;

// functions are generated by GPT
void moveDisk(int disk, int source, int destination) {
    cout << source << ' ' << destination << '\n';
}

void hanoi(int disks, int source, int auxiliary, int destination) {
    if (disks == 1) {
        moveDisk(disks, source, destination);
    } else {
        hanoi(disks - 1, source, destination, auxiliary);
        moveDisk(disks, source, destination);
        hanoi(disks - 1, auxiliary, source, destination);
    }
}

int32_t main() {

    ios;
    int n; cin >> n;
    cout << pow(2, n) - 1 << '\n';
    hanoi(n, 1, 2, 3);
    return 0;
}
